baseurl: ""
permalink: pretty
title: "TorchDrug"

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "assets/images/logo/logo-mobile.svg"
  desktop: "assets/images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright: "MilaGraph"

seo:
  meta_og_title: "Jekyll Serif Theme"
  meta_og_type: "website"
  meta_og_url: "https://jekyll-serif-theme.netlify.app"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Jekyll Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

include:
  - _pages
  # sphinx
  - .doctrees
  - _downloads
  - _images
  - _modules
  - _sources
  - _static